// Birth-year context is approximate and assumes the current year is 2026.
// Facts were curated against official timelines from NASA, Apple, Nintendo,
// LEGO, the Academy of Motion Picture Arts and Sciences, and historical archives.
export const AGE_LINES = [
  "",
  "Around 2025, Nintendo Switch 2 launched. You arrived with upgraded hardware.",
  "Around 2024, Tetris turned 40—and those falling blocks still had everyone stressed.",
  "Around 2023, The Super Mario Bros. Movie made a billion-dollar warp jump.",
  "Around 2022, the James Webb telescope sent back its first full-color cosmic images.",
  "Around 2021, Perseverance landed on Mars carrying a tiny helicopter named Ingenuity.",
  "Around 2020, PlayStation 5 and Xbox Series X started a fresh console war.",
  "Around 2019, humanity photographed a black hole for the first time. Very photogenic void.",
  "Around 2018, Spider-Man: Into the Spider-Verse made comic-book animation look brand new.",
  "Around 2017, Nintendo Switch launched and made missing your train way more entertaining.",
  "Around 2016, Pokémon GO convinced millions of people to willingly go outside.",
  "Around 2015, Apple Watch launched and wrists started judging everyone’s activity rings.",
  "Around 2014, the Ice Bucket Challenge soaked the internet for a genuinely good cause.",
  "Around 2013, Frozen arrived and one song refused to leave civilization alone.",
  "Around 2012, Curiosity landed on Mars using a rocket-powered sky crane. Completely normal.",
  "Around 2011, Minecraft officially launched. The first night was still mostly screaming.",
  "Around 2010, the first iPad arrived and everyone immediately poked the giant screen.",
  "Around 2009, Minecraft’s first public version appeared with more blocks than instructions.",
  "Around 2008, Apple’s App Store opened with about 500 apps. Tiny beginning, huge screen time.",
  "Around 2007, the original iPhone debuted and made physical keyboards look nervous.",
  "Around 2006, Nintendo Wii launched and living rooms became accidental bowling alleys.",
  "Around 2005, YouTube launched. The first upload was only 19 seconds long.",
  "Around 2004, Nintendo DS arrived with two screens because one apparently wasn’t chaotic enough.",
  "Around 2003, Finding Nemo hit theaters. Parents have been checking fish tanks ever since.",
  "Around 2002, Xbox Live launched and strangers began explaining exactly how you should play.",
  "Around 2001, the first iPod promised 1,000 songs in your pocket. Pockets peaked early.",
  "Around 2000, PlayStation 2 launched and became the best-selling home console ever.",
  "Around 1999, SpongeBob debuted. Bikini Bottom has somehow aged less than all of us.",
  "Around 1998, Google was founded in a garage. The garage had excellent search results.",
  "Around 1997, the first Harry Potter book arrived in the UK. Owls got suspiciously popular.",
  "Around 1996, Pokémon launched in Japan and Nintendo 64 introduced a very strange controller.",
  "Around 1995, Toy Story became the first fully computer-animated feature film.",
  "Around 1994, the original PlayStation launched in Japan and memory cards became precious cargo.",
  "Around 1993, Doom arrived and office computers suddenly had a very important second job.",
  "Around 1992, the first SMS text said “Merry Christmas.” No emoji, somehow.",
  "Around 1991, the World Wide Web opened beyond CERN. Tabs were still an innocent concept.",
  "Around 1990, Hubble launched and immediately gave space a much better camera.",
  "Around 1989, Game Boy launched with a green screen and absolutely elite battery life.",
  "Around 1988, Sega Mega Drive launched in Japan. Console arguments gained new material.",
  "Around 1987, the GIF format was introduced. The pronunciation argument never recovered.",
  "Around 1986, The Legend of Zelda launched in Japan. Smashing random pots became heroic.",
  "Around 1985, Super Mario Bros. and the NES helped revive home gaming in North America.",
  "Around 1984, Tetris was created. Productivity has been falling into place ever since.",
  "Around 1983, Nintendo’s Famicom and Mario Bros. arrived. Plumbing became an action career.",
  "Around 1982, E.T. became the year’s biggest movie and phoned home without unlimited minutes.",
  "Around 1981, Donkey Kong introduced Mario—back when his résumé just said “Jumpman.”",
  "Around 1980, Pac-Man arrived and made eating dots under pressure look fun.",
  "Around 1979, the Sony Walkman made carrying your personal soundtrack feel futuristic.",
  "Around 1978, Space Invaders landed in arcades and high scores became serious business.",
  "Around 1977, Star Wars hit theaters. Opening text has never felt more dramatic.",
  "Around 1976, Apple was founded. The first headquarters was a bedroom, not a spaceship.",
  "Around 1975, Jaws helped invent the summer blockbuster and ruined peaceful swimming.",
  "Around 1974, the Rubik’s Cube was invented. So was pretending you almost solved it.",
  "Around 1973, the first handheld mobile-phone call was made on a device weighing over two pounds.",
  "Around 1972, Pong and the Magnavox Odyssey brought video games into the living room.",
  "Around 1971, the first network email was sent. The exact message was immediately forgotten.",
  "Around 1970, the first Earth Day drew millions of people into the streets.",
  "Around 1969, Apollo 11 reached the Moon with less computing power than a modern calculator.",
  "Around 1968, 2001: A Space Odyssey made artificial intelligence calmly terrifying.",
  "Around 1967, engineers built a handheld calculator prototype. “Handheld” was doing work.",
  "Around 1966, Star Trek premiered and boldly launched decades of arguments about captains.",
  "Around 1965, Alexei Leonov performed the first spacewalk—and nearly couldn’t fit back inside.",
  "Around 1964, BASIC was created so ordinary people could tell computers what to do.",
  "Around 1963, the compact cassette debuted. Mixtape culture was officially loading.",
  "Around 1962, Spacewar! became one of the earliest influential computer games.",
  "Around 1961, Yuri Gagarin became the first human in space. His trip took 108 minutes.",
  "Around 1960, the first working laser fired. Scientists called it a solution seeking a problem.",
  "Around 1959, Barbie debuted at the New York Toy Fair with an extremely full calendar.",
  "Around 1958, Tennis for Two turned an oscilloscope into one of the earliest video-game displays.",
  "Around 1957, Sputnik became the first artificial satellite and beeped its way around Earth.",
  "Around 1956, IBM’s first commercial hard drive stored 5 MB and weighed more than a ton.",
  "Around 1955, Disneyland opened and the first day included traffic, heat, and fake tickets.",
  "Around 1954, the first mass-market transistor radio made music genuinely pocket-sized.",
  "Around 1953, the DNA double-helix model was published. Humanity found its source code.",
  "Around 1952, Mr. Potato Head became the first toy advertised directly to children on TV.",
  "Around 1951, UNIVAC I became one of America’s first commercial computers.",
  "Around 1950, Peanuts debuted with Charlie Brown already having a complicated week.",
  "Around 1949, LEGO introduced its first plastic Automatic Binding Bricks.",
  "Around 1948, Columbia introduced the long-playing vinyl record. Albums finally got room to breathe.",
  "Around 1947, the transistor was demonstrated. Tiny electronics were about to take over.",
  "Around 1946, ENIAC was unveiled with about 18,000 vacuum tubes and zero portability.",
  "Around 1945, a melted candy bar helped inspire microwave cooking. Snack science won.",
  "Around 1944, Colossus was operating as one of the world’s first programmable electronic computers.",
  "Around 1943, the Slinky was invented after a spring accidentally tumbled from a shelf.",
  "Around 1942, Little Golden Books launched at 25 cents each. Bedtime got a budget option.",
  "Around 1941, M&M’s entered production with a shell designed to keep chocolate off fingers.",
  "Around 1940, Tom and Jerry debuted and immediately chose cartoon violence.",
  "Around 1939, The Wizard of Oz reached theaters and made color feel like actual magic.",
  "Around 1938, Superman debuted in Action Comics #1 and changed capes forever.",
  "Around 1937, Snow White became the first full-length cel-animated feature.",
  "Around 1936, the BBC began regular high-definition television broadcasts. That meant 240 lines.",
  "Around 1935, Parker Brothers began selling Monopoly. Family negotiations have never recovered.",
  "Around 1934, Donald Duck made his screen debut already sounding mildly furious.",
  "Around 1933, King Kong climbed the Empire State Building and cinema found a giant new problem.",
  "Around 1932, LEGO was founded in Denmark. The name comes from words meaning “play well.”",
  "Around 1931, the Empire State Building opened after only about 13 months of construction.",
  "Around 1930, the first FIFA World Cup kicked off in Uruguay with just 13 teams.",
  "Around 1929, the first Academy Awards ceremony lasted about 15 minutes. Efficient Hollywood.",
  "Around 1928, Steamboat Willie gave Mickey Mouse his famous public debut.",
  "Around 1927, The Jazz Singer brought synchronized dialogue to feature-film audiences.",
] as const;

export function getAgeLine(age: number): string {
  const safeAge = Math.max(1, Math.min(99, Math.round(age)));
  return AGE_LINES[safeAge];
}
