export const AGE_LINES = [
  "",
  "Dang, you’re basically a newborn. Tiny legend.",
  "Two years in and already running the lobby.",
  "Three: tiny human, maximum chaos.",
  "Four years old. Zero indoor voice.",
  "Five: crayons remain a valid strategy.",
  "Six and already speedrunning childhood.",
  "Seven: lucky number, sticky fingers.",
  "Eight: officially too fast for the hallway.",
  "Nine: one level away from double digits.",
  "Double digits. Tiny age, huge milestone.",
  "Eleven: strong opinions about the best snack.",
  "Twelve: the final pre-teen boss battle.",
  "Thirteen: teenager mode has been activated.",
  "Fourteen: confidence high, battery somehow low.",
  "Fifteen: one playlist from a personality change.",
  "Sixteen: main-character permissions granted.",
  "Seventeen: practically grown, allegedly.",
  "Eighteen: adult mode unlocked. Tutorial still missing.",
  "Nineteen: technically grown, spiritually buffering.",
  "Twenty: new decade, same mysterious sleep schedule.",
  "Twenty-one: the full menu is now unlocked.",
  "Twenty-two: everything will be alright… probably.",
  "Twenty-three: nobody likes paperwork at this age.",
  "Twenty-four: prime time for suspiciously bold decisions.",
  "Twenty-five: quarter-century achievement unlocked.",
  "Twenty-six: capable, thriving, forgetting why you entered rooms.",
  "Twenty-seven: the cool kind of responsible.",
  "Twenty-eight: thriving with several tabs still open.",
  "Twenty-nine: one last lap before level thirty.",
  "Thirty: premium adulthood begins now.",
  "Thirty-one: thirty, plus one year of patch notes.",
  "Thirty-two: experienced enough to bring a charger.",
  "Thirty-three: balanced somewhere between plans and naps.",
  "Thirty-four: still young, now with better snacks.",
  "Thirty-five: halfway to seventy and looking efficient.",
  "Thirty-six: old enough to appreciate a quiet room.",
  "Thirty-seven: wisdom rising, knees negotiating.",
  "Thirty-eight: experienced chaos coordinator.",
  "Thirty-nine: the final boss before forty.",
  "Forty: classic edition, freshly remastered.",
  "Forty-one: level forty with bonus content.",
  "Forty-two: apparently the answer to everything.",
  "Forty-three: refined, upgraded, and still improvising.",
  "Forty-four: double fours. Extremely symmetrical.",
  "Forty-five: halfway to ninety, nowhere near finished.",
  "Forty-six: vintage energy, modern problems.",
  "Forty-seven: too seasoned for weak game-night rules.",
  "Forty-eight: four dozen years of plot development.",
  "Forty-nine: seven squared. Mathematically elite.",
  "Fifty: half a century and fully operational.",
  "Fifty-one: classic model with excellent mileage.",
  "Fifty-two: one year for every card in the deck.",
  "Fifty-three: rare edition—few patch notes required.",
  "Fifty-four: experienced enough to spot the tutorial trap.",
  "Fifty-five: double fives and unmistakable boss energy.",
  "Fifty-six: eight times seven. The numbers approve.",
  "Fifty-seven: seasoned, stylish, difficult to surprise.",
  "Fifty-eight: almost sixty, still choosing the soundtrack.",
  "Fifty-nine: final warm-up before the sixties.",
  "Sixty: six decades of premium lore.",
  "Sixty-one: still collecting wins and good stories.",
  "Sixty-two: calm exterior, competitive interior.",
  "Sixty-three: nine times seven—certified lucky math.",
  "Sixty-four: perfect square, classic game-console energy.",
  "Sixty-five: retirement age somewhere, chaos age everywhere.",
  "Sixty-six: double sixes. The dice are listening.",
  "Sixty-seven: too experienced to fall for obvious bait.",
  "Sixty-eight: one step from the internet’s favorite number.",
  "Sixty-nine: nice. Moving respectfully along.",
  "Seventy: seven decades, zero need for a tutorial.",
  "Seventy-one: veteran status with bonus charisma.",
  "Seventy-two: six dozen years of excellent side quests.",
  "Seventy-three: prime number, prime energy.",
  "Seventy-four: still upgrading the character build.",
  "Seventy-five: three-quarter-century achievement unlocked.",
  "Seventy-six: experienced enough to rewrite the rules.",
  "Seventy-seven: double lucky and fully legendary.",
  "Seventy-eight: thirteen times six—mischief checks out.",
  "Seventy-nine: one victory lap before eighty.",
  "Eighty: eight decades. Hall-of-fame behavior.",
  "Eighty-one: nine squared. Mathematically unstoppable.",
  "Eighty-two: vintage build, elite reliability.",
  "Eighty-three: prime age, premium edition.",
  "Eighty-four: seven dozen years of stories.",
  "Eighty-five: certified legend with excellent range.",
  "Eighty-six: still here, still raising the difficulty.",
  "Eighty-seven: rare character unlocked.",
  "Eighty-eight: double infinity standing tall.",
  "Eighty-nine: prime number and top-tier status.",
  "Ninety: nine decades. The lore is enormous.",
  "Ninety-one: thirteen times seven—extra lucky.",
  "Ninety-two: classic, collected, still in the game.",
  "Ninety-three: ninety years plus a three-year victory lap.",
  "Ninety-four: elite longevity achievement unlocked.",
  "Ninety-five: a full century is visible from here.",
  "Ninety-six: eight dozen years of plot twists.",
  "Ninety-seven: prime age, legendary résumé.",
  "Ninety-eight: two points away from triple digits.",
  "Damn, you’re ancient—in the legendary way.",
] as const;

export function getAgeLine(age: number): string {
  const safeAge = Math.max(1, Math.min(99, Math.round(age)));
  return AGE_LINES[safeAge];
}
